"""Constantes do modulo ANVISA."""

from __future__ import annotations

# --- URLs ---

ANVISA_MEDICAMENTOS_URL = (
    "https://dados.anvisa.gov.br/dados/CONSULTAS/PRODUTOS/TA_CONSULTA_MEDICAMENTOS.CSV"
)

# --- DuckDB ---

ANVISA_DB_FILENAME = "anvisa.duckdb"
ANVISA_REFRESH_DAYS = 30  # re-download CSV se mais antigo que isso

# --- CSV ---

CSV_DELIMITER = ";"
CSV_ENCODING = "latin-1"

COL_REGISTRO = "NU_REGISTRO_PRODUTO"
COL_NOME = "NO_PRODUTO"
COL_SUBSTANCIAS = "SUBSTANCIAS_MEDICAMENTOS"
COL_CATEGORIA = "DS_TIPO_CATEGORIA_REGULATORIA"
COL_REFERENCIA = "DS_REFERENCIA"
COL_ATC = "CO_ATC"
COL_TARJA = "CO_TARJA"
COL_COMPLEMENTO = "COMPLEMENTO"
COL_EMPRESA = "NO_RAZAO_SOCIAL_EMPRESA"

REQUIRED_COLUMNS = {COL_REGISTRO, COL_NOME, COL_SUBSTANCIAS}

# --- Normalização de acentos ---

ACCENT_MAP: dict[str, str] = {
    "Á": "A",
    "À": "A",
    "Â": "A",
    "Ã": "A",
    "Ä": "A",
    "É": "E",
    "È": "E",
    "Ê": "E",
    "Ë": "E",
    "Í": "I",
    "Ì": "I",
    "Î": "I",
    "Ï": "I",
    "Ó": "O",
    "Ò": "O",
    "Ô": "O",
    "Õ": "O",
    "Ö": "O",
    "Ú": "U",
    "Ù": "U",
    "Û": "U",
    "Ü": "U",
    "Ç": "C",
    "Ñ": "N",
}

# --- Mapeamento PT ↔ EN ---
# Nomes de drogas que diferem entre português e inglês (INN).
# Inclui formas base e sais comuns.

NOME_PT_EN: dict[str, str] = {
    # Analgésicos / anti-inflamatórios
    "DIPIRONA": "METAMIZOLE",
    "DIPIRONA SODICA": "METAMIZOLE SODIUM",
    "DIPIRONA MONOIDRATADA": "METAMIZOLE",
    "PARACETAMOL": "ACETAMINOPHEN",
    "ÁCIDO ACETILSALICÍLICO": "ASPIRIN",
    "ACIDO ACETILSALICILICO": "ASPIRIN",
    "NIMESULIDA": "NIMESULIDE",
    "DICLOFENACO": "DICLOFENAC",
    "DICLOFENACO SODICO": "DICLOFENAC SODIUM",
    "DICLOFENACO POTASSICO": "DICLOFENAC POTASSIUM",
    "IBUPROFENO": "IBUPROFEN",
    "CLORIDRATO DE TRAMADOL": "TRAMADOL HYDROCHLORIDE",
    "TRAMADOL": "TRAMADOL",
    # Cardiovascular
    "LOSARTANA": "LOSARTAN",
    "LOSARTANA POTASSICA": "LOSARTAN POTASSIUM",
    "ANLODIPINO": "AMLODIPINE",
    "BESILATO DE ANLODIPINO": "AMLODIPINE BESYLATE",
    "ENALAPRIL": "ENALAPRIL",
    "MALEATO DE ENALAPRIL": "ENALAPRIL MALEATE",
    "ATENOLOL": "ATENOLOL",
    "SINVASTATINA": "SIMVASTATIN",
    "ATORVASTATINA": "ATORVASTATIN",
    "AMIODARONA": "AMIODARONE",
    "CLORIDRATO DE AMIODARONA": "AMIODARONE HYDROCHLORIDE",
    "APIXABANA": "APIXABAN",
    # Gastrointestinal
    "OMEPRAZOL": "OMEPRAZOLE",
    "PANTOPRAZOL": "PANTOPRAZOLE",
    # Metabolismo
    "CLORIDRATO DE METFORMINA": "METFORMIN HYDROCHLORIDE",
    "METFORMINA": "METFORMIN",
    "SEMAGLUTIDA": "SEMAGLUTIDE",
    "TIRZEPATIDA": "TIRZEPATIDE",
    "EMPAGLIFLOZINA": "EMPAGLIFLOZIN",
    # Anestésicos e adjacentes
    "PROPOFOL": "PROPOFOL",
    "CETAMINA": "KETAMINE",
    "CLORIDRATO DE CETAMINA": "KETAMINE HYDROCHLORIDE",
    "DEXMEDETOMIDINA": "DEXMEDETOMIDINE",
    "CLORIDRATO DE DEXMEDETOMIDINA": "DEXMEDETOMIDINE HYDROCHLORIDE",
    "MIDAZOLAM": "MIDAZOLAM",
    "MALEATO DE MIDAZOLAM": "MIDAZOLAM MALEATE",
    "ETOMIDATO": "ETOMIDATE",
    "SUCCINILCOLINA": "SUCCINYLCHOLINE",
    "CLORETO DE SUCCINILCOLINA": "SUCCINYLCHOLINE CHLORIDE",
    "ROCURONIO": "ROCURONIUM",
    "BROMETO DE ROCURONIO": "ROCURONIUM BROMIDE",
    "SUGAMADEX": "SUGAMMADEX",
    "SEVOFLURANO": "SEVOFLURANE",
    "DESFLURANO": "DESFLURANE",
    "FENTANILA": "FENTANYL",
    "CITRATO DE FENTANILA": "FENTANYL CITRATE",
    "REMIFENTANILA": "REMIFENTANIL",
    "CLORIDRATO DE REMIFENTANILA": "REMIFENTANIL HYDROCHLORIDE",
    "BUPIVACAINA": "BUPIVACAINE",
    "CLORIDRATO DE BUPIVACAINA": "BUPIVACAINE HYDROCHLORIDE",
    "LIDOCAINA": "LIDOCAINE",
    "CLORIDRATO DE LIDOCAINA": "LIDOCAINE HYDROCHLORIDE",
    "NOREPINEFRINA": "NOREPINEPHRINE",
    "BITARTARATO DE NOREPINEFRINA": "NOREPINEPHRINE BITARTRATE",
    "EFEDRINA": "EPHEDRINE",
    "ATROPINA": "ATROPINE",
    "SULFATO DE ATROPINA": "ATROPINE SULFATE",
    "NEOSTIGMINA": "NEOSTIGMINE",
    "METILBROMETO DE NEOSTIGMINA": "NEOSTIGMINE METHYLSULFATE",
    "ONDANSETRONA": "ONDANSETRON",
    "CLORIDRATO DE ONDANSETRONA": "ONDANSETRON HYDROCHLORIDE",
    "DEXAMETASONA": "DEXAMETHASONE",
    "FOSFATO DISSODICO DE DEXAMETASONA": "DEXAMETHASONE SODIUM PHOSPHATE",
    "HIDROCORTISONA": "HYDROCORTISONE",
    "SUCCINATO SODICO DE HIDROCORTISONA": "HYDROCORTISONE SODIUM SUCCINATE",
    # Antibióticos
    "CEFALEXINA": "CEPHALEXIN",
    "AMOXICILINA": "AMOXICILLIN",
    "AZITROMICINA": "AZITHROMYCIN",
    "CIPROFLOXACINO": "CIPROFLOXACIN",
    "LEVOFLOXACINO": "LEVOFLOXACIN",
    "CLORIDRATO DE CIPROFLOXACINO": "CIPROFLOXACIN HYDROCHLORIDE",
    # Neuropsiquiatria
    "ARIPIPRAZOL": "ARIPIPRAZOLE",
    "GABAPENTINA": "GABAPENTIN",
    "LEVETIRACETAM": "LEVETIRACETAM",
    "VALPROATO DE SODIO": "VALPROIC ACID",
    "ÁCIDO VALPROICO": "VALPROIC ACID",
    "ACIDO VALPROICO": "VALPROIC ACID",
    "TOPIRAMATO": "TOPIRAMATE",
    "MODAFINILA": "MODAFINIL",
    "CLOZAPINA": "CLOZAPINE",
    "QUETIAPINA": "QUETIAPINE",
    "FUMARATO DE QUETIAPINA": "QUETIAPINE FUMARATE",
    "ZOLPIDEM": "ZOLPIDEM",
    "HEMITARTARATO DE ZOLPIDEM": "ZOLPIDEM TARTRATE",
    # Imunobiológicos / outros
    "RITUXIMABE": "RITUXIMAB",
    "NIVOLUMABE": "NIVOLUMAB",
    "PEMBROLIZUMABE": "PEMBROLIZUMAB",
    "ADALIMUMABE": "ADALIMUMAB",
    "DUPILUMABE": "DUPILUMAB",
    "TOFACITINIBE": "TOFACITINIB",
    "CITRATO DE TOFACITINIBE": "TOFACITINIB CITRATE",
    "INSULINA": "INSULIN",
    "INSULINA HUMANA": "INSULIN HUMAN",
    "ISOTRETINOINA": "ISOTRETINOIN",
    "FINASTERIDA": "FINASTERIDE",
    "MONTELUCASTE": "MONTELUKAST",
    "MONTELUCASTE DE SODIO": "MONTELUKAST SODIUM",
    "CETIRIZINA": "CETIRIZINE",
    "HIDROXICLOROQUINA": "HYDROXYCHLOROQUINE",
    "SULFATO DE HIDROXICLOROQUINA": "HYDROXYCHLOROQUINE SULFATE",
}

# Reverso: EN → PT (primeiro match)
NOME_EN_PT: dict[str, str] = {v: k for k, v in NOME_PT_EN.items()}
